<?php

// config
$less = new lessc;
$less->setFormatter('compressed');

// desktop
$less_input = 'assets/css/admin/common.less';
$css_file['common'] = $less->compileFile($less_input);

$stylesheet = '<style type="text/css">'.$css_file['common'].'</style>';

?>


<!DOCTYPE html>
<html>
<head>
	<title>Admin - <?=CLIENT_NAME?></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	
	<!-- CSS -->
	<?=$stylesheet?>
	<link rel="stylesheet" href="/assets/css/admin/cleanbox.css?<?=APP_VERSION?>">
</head>
<body id="<?=$this->body_class_name?>" <?=$this->data['body_attr']?>>

