	


	</main>



	<!-- Footer -->
	<footer>&copy; Lema</footer>



	<!-- JS -->
	<script src="/assets/js/admin/plugins.js?<?=APP_VERSION?>"></script>
	<script src="/assets/js/admin/cleanbox.js?<?=APP_VERSION?>"></script>
	<script src="/assets/js/admin/common.js?<?=APP_VERSION?>"></script>
	<!-- <script src="/assets/js/admin/common-delete.js?<?=APP_VERSION?>"></script> -->




<?php $this->template('foot'); ?>