
	<!-- header -->
	<div class="content-header clearfix">
		<div class="left">
			<h1>
				<?=$this->data['form_titulo']?>
				<!-- <span><?=($this->data['endereco_id'] ? 'REF. '.$this->data['endereco_id'] : '')?></span> -->
			</h1>
		</div>

		<div class="right">
			<a class="close" rel="cleanbox-close" href="#">
				<svg class="transition" viewBox="0 0 24 24" style="background-color:#ffffff00" version="1.1"
					xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve"
					x="0px" y="0px" width="24px" height="24px">
					<g>
						<path d="M 1 1 L 23 23 " stroke="#ffffff" stroke-width="2" fill="none"/>
						<path d="M 23 1 L 1 23 " stroke="#ffffff" stroke-width="2" fill="none"/>
					</g>
				</svg>
			</a>
		</div>
	</div>