<?php

// config
$less = new lessc;
$less->setFormatter('compressed');
$less->setVariables([ 'cor_fundo' => '(0,0,0)']);

// desktop
$less_input = 'assets/css/common.less.css';
$css_output = 'assets/css/1001/common.css';
$css_file['common'] = $less->compileFile($less_input);

// mobile
$less_input = 'assets/css/common-mobile.less.css';
$css_output = 'assets/css/1001/common-mobile.css';
$css_file['common-mobile'] = $less->compileFile($less_input);

$stylesheet = '<style type="text/css">'.$css_file['common'].$css_file['common-mobile'].'</style>';

?>


<!DOCTYPE html>
<html>
<head>
	<title><?=$this->page_title?></title>
	<meta name="viewport" content="width=320px, user-scalable=no, initial-scale=1">

	<!-- CSS -->
	<?=$stylesheet?>

</head>
<body id="<?=$this->body_class_name?>" <?=$data['body_attr']?>>