<?=$this->template('default-head'); ?>



	<!-- header -->
	<header id="main-header">
		<div class="header-bar wrap">
			<div class="header-bar-logo">
				<a href="/<?=$this->data['evento_id']?>" class="<?=($this->data['iniciais'] ? '' : 'has-logotipo' )?>">
					<?=$this->data['iniciais']?>
					<img src="<?=$this->data['imagem_logo']?>" alt="<?=$this->data['titulo']?>" />
				</a>
			</div>
			<div class="header-bar-sound <?=($this->data['musica'] ? '' : 'none' )?>">
				<ul>
					<li><a href="javascript:;" class="icon-sound bounce animated infinite cursor-default"></a></li>
					<li class="division"></li>
					<li><a href="javascript:;" class="icon-sound-play"></a></li>
					<li><a href="javascript:;" class="icon-sound-pause"></a></li>
				</ul>
				<audio controls autoplay>
					<source src="<?=$this->data['musica']?>" type="audio/mpeg">
					Browser doesn't support audio.
				</audio>
			</div>
		</div>
		<div class="header-photos">
			<ul class="photos-base flex-flow">
				<?=$this->data['fotos']?>
			</ul>
			<div id="photo-loader" class="none">
				<?=$this->data['fotos_loader']?>
			</div>
		</div>
	</header>